root: true
parser: babel-eslint
parserOptions:
  sourceType: module
  requireConfigFile: false
  ecmaFeatures:
    impliedStrict: true
    jsx: true
settings:
  import/resolver:
    node:
      extensions:
        - .js
        - .jsx
        - .ts
        - .tsx
  react:
    version: detect
env:
  es2020: true
  commonjs: true
  browser: true
  node: true
  serviceworker: true
  jest: true
plugins:
  - babel
  - ramda
  - redux-saga
  - react-hooks
  - emotion
extends:
  - eslint:recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:react/recommended
  - plugin:jsx-a11y/recommended
  - plugin:ramda/recommended
  - plugin:redux-saga/recommended
rules:
  max-len:
    - 1
    - code: 100
      ignoreComments: true
  no-console: warn
  no-alert: warn
  no-debugger: warn
  new-cap: 'off'
  no-invalid-this: 'off'
  object-curly-spacing: 'off'
  quotes: 'off'
  semi: 'off'
  rest-spread-spacing: warn
  babel/new-cap: warn
  babel/no-invalid-this: warn
  babel/object-curly-spacing:
    - warn
    - always
  babel/quotes:
    - error
    - single
    - allowTemplateLiterals: true
  babel/semi: error
  import/order:
    - warn
    - groups:
      - builtin
      - external
      - internal
      - parent
      - sibling
      - index
  import/newline-after-import: warn
  react/boolean-prop-naming: warn
  react/no-array-index-key: warn
  react/no-unused-prop-types: warn
  react/no-unused-state: warn
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: warn
  emotion/no-vanilla: error
  emotion/import-from-emotion: error
  emotion/styled-import: error
  emotion/syntax-preference:
    - warn
    - string
overrides:
  - files:
      - '*.ts'
      - '*.tsx'
    parser: '@typescript-eslint/parser'
    parserOptions:
      project: './tsconfig.json'
    extends:
      - plugin:import/typescript
      - plugin:@typescript-eslint/eslint-recommended
      - plugin:@typescript-eslint/recommended
    rules:
      react/prop-types: 'off'
      '@typescript-eslint/explicit-function-return-type': 'off'
      '@typescript-eslint/prefer-namespace-keyword': 'off'
  - files:
      - src/index.*
      - src/webpack/builder/**
      - src/server/**
    rules:
      no-console: 'off'
      no-restricted-syntax:
        - error
        - selector: CallExpression[callee.object.name='console'][callee.property.name!=/^(log|warn|error|info|trace)$/]
          message: Unexpected property on console object was called
