GET http://localhost:3000

###
GET http://localhost:3000/source

###
GET http://localhost:3000/api/sse

###
GET http://localhost:3000/api/sse/notices

###
POST http://localhost:3000/api/sse
Content-Type: application/json

{ "text": "Hello world!" }

###
PUT http://localhost:3000/api/sse/:id
Content-Type: application/json

{ "text": "Hi world!" }

###
DELETE http://localhost:3000/api/sse/notices/:id

###
DELETE http://localhost:3000/api/sse/notices
