version: "3.9"
services:
  todos:
    container_name: todos-app-dev
    image: todos-app-dev:latest
    build:
      context: .
      target: dev
    ports:
      - 3000:3000
      - 127.0.0.1:9229:9229
    volumes:
      - ./src:/app/base/src
      - ./public:/app/base/public
